### ISSUE TITLE
Any help is appreciated

### ISSUE THREAD

**Issue by mxride** [kadena-io/chainweb-node#1440] opened 2022-05-18 15:34 UTC
I used a minimal config.yaml and syned the Chainweb-node.
Had issue getting mining to work, so I generated a complete new config.yaml.
Now when I start chainweb-node wit the new complete config.yaml I see this
Thanks in advance

![image](https://user-images.githubusercontent.com/771496/169087467-2c176a90-51e5-41d3-9c98-c9e2f226947d.png)

Trying to start Chainweb-mining
![image](https://user-images.githubusercontent.com/771496/169087303-fa4e58e9-394e-433d-8d69-f68992a44b56.png)

**Comment by LindaOrtega** [comment] 2022-05-23 16:16
Hi @mxride, I answered a similar question you had in another issue here: https://github.com/kadena-io/chainweb-node/issues/1307#issuecomment-1133043806

Let me know if you are still unable to mine to your node.

**Comment by mxride** [comment] 2022-05-23 18:29
@LindaOrtega this what I'm seeing when I run ./chainweb-node --config-file=config.yaml.TEST
Once its running I never seem t get a repose when checking the cut height.
Would love to do a screen share with you so you can get me straight on this. Been trying to get this running for weeks.
Thanks in advance

![image](https://user-images.githubusercontent.com/771496/169883603-6bf476db-b528-45d0-85af-0e24926ff63e.png)


![image](https://user-images.githubusercontent.com/771496/169883435-482ab571-6ccc-4f16-ae13-27ba79c755c6.png)

**Comment by edmundnoble** [comment] 2023-01-10 00:28
The issue is likely that your pubkey is not set as one of the miners in your config.yaml. It should contain a stanza like this:
```yaml
chainweb:
  mining:
    coordination:
      enabled: true
      miners: 
        - mypubkey
```

**Comment by chessai** [comment] 2023-06-13 22:28
@mxride Did Edmund's response above solve your issue?

**Comment by chessai** [comment] 2024-01-09 21:25
Closing. Feel free to re-open if this is still an issue.

**Closed by chessai** 2024-01-09 21:25 UTC
