### ISSUE TITLE
only {key} accounts allowed for mining (not k: or named accounts)

### ISSUE THREAD

**Issue by imanolbarberia** [kadena-io/chainweb-node#1298] opened 2021-11-12 23:43 UTC
I am working on having the mining client set up. I had the node set up like this, regarding the mining configuration:
```
  mining:
    coordination:
      enabled: true
      mode: private
      limit: 1200
      miners: 
      - account: k:abc
        predicate: keys-all
        public-keys:
        - abc
```
I launched the mining client with the following command:
```
chainweb-mining-client --no-tls \
--public-key=abc \
--node=localhost:1848 \
--log-level=info \
--thread-count=2 \
--worker=stratum \
--stratum-port=1917
```

But when launching the mining client, I was receiving this error:
```
 (StatusCodeException (Response {responseStatus = Status {statusCode = 403, statusMessage = "Forbidden"}, responseVersion = HTTP/1.1, responseHeaders = [("Transfer-Encoding","chunked"),("Date","Fri, 12 Nov 2021 23:10:34 GMT"),("Server","Warp/3.3.17"),("X-Server-Timestamp","1636758634"),("X-Chainweb-Node-Version","2.11")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose, responseOriginalRequest = Request {
  host                 = "localhost"
  port                 = 1848
  secure               = False
  requestHeaders       = [("content-type","application/json")]
  path                 = "chainweb/0.0/mainnet01/mining/work"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
  proxySecureMode      = ProxySecureWithConnect
}
}) "Unauthorized Miner: abc")
```

So I tried and changed the miner account in the node configuration, from `k:abc` to `abc` and it started working properly. I also tried using a named account (with a name different from a key) and it didn't work either.

As additional info, I used the binary **chainweb-node v2.11** available as a release in the github repo, and for the mining client, I built it myself with **cabal 3.6.2.0** (installed via **ghcup v0.1.17.3**). 

Let me know if any additional info or tests are required.

**Comment by larskuhtz** [comment] 2021-11-21 19:37
This is an issue of [chainweb-mining-client](https://github.com/kadena-io/chainweb-mining-client), that is resolved in [this PR](https://github.com/kadena-io/chainweb-mining-client/pull/17).

 Chainweb-node node supports `k:` accounts for mining in the configuration.

#1311 adds support for a simplified mining configuration via the command and uses `k:` accounts by default.

**Comment by larskuhtz** [comment] 2021-11-21 19:39
Closing this issue because the issue is already tracked in the chainweb-mining-client repo [in this issue](https://github.com/kadena-io/chainweb-mining-client/issues/16) and resolved in [this PR](https://github.com/kadena-io/chainweb-mining-client/pull/17).

**Closed by larskuhtz** 2021-11-21 19:39 UTC
