### ISSUE TITLE
chainweb-data is not indexing from a fully synced node after the forced 06Sept update

### ISSUE THREAD

**Issue by Jad-KMC** [kadena-io/chainweb-node#1735] opened 2023-09-11 19:13 UTC
The testnet wasn't syncing as of a few weeks ago, which raised concerns. Now the mainnet data nodes seem to have stopped indexing after the forced update. I've checked with others and they are having the same issue.

Additionally, https://explorer.chainweb.com is only showing events as of the 6th of september, and all three of my nodes are not displaying these events either. 

Running chainweb-data fill just returns "filling 0 gaps and 0 blocks" and "filled in 0 missing blocks"

**Comment by trendzetter** [comment] 2023-09-14 13:59
To my understanding this issue was resolved by updating chainweb-data instance as well

**Comment by enobayram** [comment] 2023-09-15 09:20
@Jad-KMC we're sorry for the indexing issue in https://explorer.chainweb.com. The update for the `chainweb-node` instance servicing the explorer's `chainweb-data` was triggered too early, causing it not to pick up the updated service date. Other than this hiccup (which is fixed now) caused by the infrastructure running the explorer + its `chainweb-data`, I'm not aware of any issue with `chainweb-data` not being able to index from a fully synced node. Can you provide more details about how you're running your node and your `chainweb-data`?

> Running chainweb-data fill just returns "filling 0 gaps and 0 blocks" and "filled in 0 missing blocks"

Are you also running a separate `chainweb-data` process in `serve` or `listen` mode at the side? Because currently the `fill` operation of `chainweb-data` fills "backwards", i.e. it will only fill missing blocks that already have their descendants in the database, which will be the case if you start `chainweb-data` in `serve` or `listen` modes after an interruption.

**Comment by mbwmbw1337** [comment] 2023-09-15 09:30
All -

If it helps, I had the exact same issue. To solve the issue here is what I did:
1. git pull both chainweb-node and chainweb-data
2. nix-build each of them
3. restart chainweb-node
4. wait 5 minutes restart chainweb-data
5. run the fill loop

I do not know what happened but on one server I had to repeat this process twice.

Regards,

Michael

**Comment by enobayram** [comment] 2023-09-15 11:32
@mbwmbw1337 Thank you for the input. 

It's hard for me to reproduce the issue based on the details provided here, and I believe also unnecessary; https://github.com/kadena-io/chainweb-data/pull/151 and https://github.com/kadena-io/chainweb-data/pull/160 have together removed all dependency on `chainweb-node`'s p2p endpoint (as mentioned in the latest CW-D changelog). `chainweb-node`'s p2p endpoint is meant to be used for inter-node communication-only, so it wouldn't be surprising for CW-N to break earlier versions of CW-D in unexpected ways and dependent on the node configuration. [The latest CW-D version (2.3.0)](https://github.com/kadena-io/chainweb-data/releases/tag/v2.3.0) avoids this issue, so upgrading to it is a good idea anyway.

> on one server I had to repeat this process twice.

I'll watch out for signs of this and dig into it if I encounter it, or I'd be happy to review logs if anybody captures them during an incident like this.

Regards,

Enis

**Comment by enobayram** [comment] 2023-09-15 11:37
As a side note;

> 1. git pull both chainweb-node and chainweb-data
> 2. nix-build each of them

Just a little tip, since `chainweb-node` and `chainweb-data` are both flakes, you can reduce these two steps down to:

* `nix build github:kadena-io/chainweb-data/v2.3.0` for CW-D
* `nix build github:kadena-io/chainweb-node/2.20` for CW-N

**Comment by mbwmbw1337** [comment] 2023-09-15 12:44
I've never had this happen before. I run over 130 chainweb node and data instances and this is the first time I've had a major issue.

Alas though all is good. I don't expect everything to be perfect. We're building out a complete CI/CD testing facility with 100% code coverage both with regression and unit tests where we will deploy the new releases into a sandbox run our tests then promote.

I am happy to share the results with you!

Michael

**Comment by mbwmbw1337** [comment] 2023-09-15 12:45
> As a side note;
> 
> 
> 
> > 1. git pull both chainweb-node and chainweb-data
> 
> > 2. nix-build each of them
> 
> 
> 
> Just a little tip, since `chainweb-node` and `chainweb-data` are both flakes, you can reduce these two steps down to:
> 
> 
> 
> * `nix build github:kadena-io/chainweb-data/v2.3.0` for CW-D
> 
> * `nix build github:kadena-io/chainweb-node/2.20` for CW-N
> 
> 

Does this actually preserve the code history and change locally? From an audit perspective we need to be able to show the code changes locally that we're using to our auditors. I know this is on GitHub but we need to be able to attest to exactly what lines are being changed each pull.

**Comment by enobayram** [comment] 2023-09-15 14:09
> I am happy to share the results with you!

Thank you, I'd be looking forward to it!

> Does this actually preserve the code history and change locally?

This way of running `nix build` doesn't require you to keep a local checkout, `nix` will take care of fetching and extracting the repo to `/nix/store` and performing the build from there. I think that makes the deployment automation more robust since using the `git` CLI in scripts and manipulating a local git checkout can be fragile. Maybe you're worried that the `v2.3.0` etc. release tags might change over time, in that case, you can instead use `nix build github:kadena-io/chainweb-node?rev=5615db59004357a68bea6bd0392832b31effc488`, which pins down the commit hash.

**Comment by chessai** [comment] 2024-01-09 21:24
This seems resolved to me. Feel free to re-open if this is not the case.

**Closed by chessai** 2024-01-09 21:24 UTC
